WebApp/Controllers/AmenityController.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebApp.Models.Amenity;

namespace WebApp.Controllers;

[Authorize(Policy = "RequireAdminRole")]
public class AmenityController : Controller
{
    private readonly HttpClient _httpClient;

    public AmenityController(IHttpClientFactory httpClientFactory)
    {
        _httpClient = httpClientFactory.CreateClient();
        _httpClient.BaseAddress = new Uri("https://localhost:44318/api/v1/");
    }

    public async Task<IActionResult> Index(string searchString, CancellationToken ct)
    {
        HttpResponseMessage response;
        if (string.IsNullOrEmpty(searchString))
        {
            response = await _httpClient.GetAsync("amenities", ct);
        }
        else
        {
            response = await _httpClient.GetAsync($"amenities/{searchString}", ct);
        }
        if (!response.IsSuccessStatusCode) return StatusCode((int)response.StatusCode);

        var responseContent = await response.Content.ReadAsStringAsync(ct);
        var amenities = JsonConvert.DeserializeObject<List<AmenityViewModel>>(responseContent);

        return View(amenities);
    }

    
    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CreateAmenityViewModel amenityViewModel, CancellationToken ct)
    {
        if (!ModelState.IsValid) return BadRequest(ModelState);

        var requestContent = JsonContent.Create(amenityViewModel);
        var response = await _httpClient.PostAsync("amenities", requestContent, ct);

        if (!response.IsSuccessStatusCode)
        {
            return StatusCode((int)response.StatusCode);
        }

        return RedirectToAction("Index");
    }

    [HttpGet]
    public async Task<IActionResult> Edit(Guid id, CancellationToken ct)
    {
        var response = await _httpClient.GetAsync($"amenities/{id}", ct);
        if (!response.IsSuccessStatusCode)
        {
            return NotFound();
        }

        var amenityViewModel = await response.Content.ReadFromJsonAsync<EditAmenityViewModel>(cancellationToken: ct);
        if (amenityViewModel == null)
        {
            return NotFound();
        }

        return View(amenityViewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(Guid id, EditAmenityViewModel viewModel, CancellationToken ct)
    {
        if (id != viewModel.Id)
        {
            return BadRequest();
        }

        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }

        var requestContent = JsonContent.Create(viewModel);
        var response = await _httpClient.PutAsync($"amenities", requestContent, ct);

        if (response.IsSuccessStatusCode)
        {
            return RedirectToAction("Index");
        }

        return StatusCode((int)response.StatusCode);
    }

    [HttpGet]
    public async Task<IActionResult> DeleteConfirmation(Guid id, CancellationToken ct)
    {
        var response = await _httpClient.GetAsync($"amenities/{id}", ct);
        if (!response.IsSuccessStatusCode)
        {
            return NotFound();
        }

        var amenityViewModel = await response.Content.ReadFromJsonAsync<DeleteAmenityViewModel>(cancellationToken: ct);
        
        if (amenityViewModel == null)
        {
            return NotFound();
        }

        return View(amenityViewModel);
    }

    [HttpPost]
    public async Task<IActionResult> Delete(Guid id, CancellationToken ct)
    {
        var response = await _httpClient.DeleteAsync($"amenities/{id}", ct);
        if (response.IsSuccessStatusCode)
        {
            return RedirectToAction("Index");
        }
        return StatusCode((int)response.StatusCode);
    }
}

WebApp/Controllers/HotelBranchController.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebApp.Models.HotelBranch;

namespace WebApp.Controllers;

[Authorize(Policy = "RequireAdminRole")]
public class HotelBranchController : Controller
{
    private readonly HttpClient _httpClient;

    public HotelBranchController(IHttpClientFactory httpClientFactory)
    {
        _httpClient = httpClientFactory.CreateClient();
        _httpClient.BaseAddress = new Uri("https://localhost:44318/api/v1/");
    }

    [HttpGet]
    public async Task<IActionResult> Index(CancellationToken ct)
    {
        var response = await _httpClient.GetAsync("hotel-branch", ct);
        
        if (!response.IsSuccessStatusCode) return StatusCode((int)response.StatusCode);

        var responseContent = await response.Content.ReadAsStringAsync(ct);
        var hotelBranches = JsonConvert.DeserializeObject<List<HotelBranchListItemViewModel>>(responseContent);

        return View(hotelBranches);
    }
    
    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CreateHotelBranchViewModel viewModel, CancellationToken ct)
    {
        if (!ModelState.IsValid) return BadRequest(ModelState);

        var requestContent = JsonContent.Create(viewModel);
        var response = await _httpClient.PostAsync("hotel-branch", requestContent, ct);
        
        if (!response.IsSuccessStatusCode)
        {
            return StatusCode((int)response.StatusCode);
        }

        return RedirectToAction("Index");
    }
    
    [HttpGet]
    public async Task<IActionResult> Edit(Guid id, CancellationToken ct)
    {
        var response = await _httpClient.GetAsync($"hotel-branch/{id}", ct);
        if (!response.IsSuccessStatusCode)
        {
            return NotFound();
        }

        var hotelBranchDto = await response.Content.ReadFromJsonAsync<HotelBranchListItemViewModel>(cancellationToken: ct);
        if (hotelBranchDto == null)
        {
            return NotFound();
        }
        var hotelBranchViewModel = new EditHotelBranchViewModel
        {
            Id = hotelBranchDto.Id,
            Name = hotelBranchDto.Name,
            Country = hotelBranchDto.Location.Country,
            City = hotelBranchDto.Location.City,
            Street = hotelBranchDto.Location.Street,
            HouseNumber = hotelBranchDto.Location.HouseNumber,
            Contacts = hotelBranchDto.Contacts
        };
        
        return View(hotelBranchViewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(Guid id, EditHotelBranchViewModel viewModel, CancellationToken ct)
    {
        if (id != viewModel.Id)
        {
            return BadRequest();
        }

        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }

        var requestContent = JsonContent.Create(viewModel);
        var response = await _httpClient.PutAsync($"hotel-branch", requestContent, ct);

        if (response.IsSuccessStatusCode)
        {
            return RedirectToAction("Index");
        }

        return StatusCode((int)response.StatusCode);
    }
    
    [HttpGet]
    public async Task<IActionResult> DeleteConfirmation(Guid id, CancellationToken ct)
    {
        var response = await _httpClient.GetAsync($"hotel-branch/{id}", ct);
        if (!response.IsSuccessStatusCode)
        {
            return NotFound();
        }

        var hotelBranchViewModel = await response.Content.ReadFromJsonAsync<DeleteHotelBranchViewModel>(cancellationToken: ct);
        
        if (hotelBranchViewModel == null)
        {
            return NotFound();
        }

        return View(hotelBranchViewModel);
    }

    [HttpPost]
    public async Task<IActionResult> Delete(Guid id, CancellationToken ct)
    {
        var response = await _httpClient.DeleteAsync($"hotel-branch/{id}", ct);
        if (response.IsSuccessStatusCode)
        {
            return RedirectToAction("Index");
        }
        return StatusCode((int)response.StatusCode);
    }
    
    [HttpGet]
    public IActionResult Details()
    {
        throw new NotImplementedException();
    }
}

WebApp/Controllers/RoomTypeAdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebApp.Models.Amenity;
using WebApp.Models.RoomType;

namespace WebApp.Controllers;

[Authorize(Policy = "RequireAdminRole")]
public class RoomTypeAdminController : Controller
{
    private readonly HttpClient _httpClient;
    private readonly IWebHostEnvironment _webHostEnvironment;

    public RoomTypeAdminController(IHttpClientFactory httpClientFactory, IWebHostEnvironment webHostEnvironment)
    {
        _httpClient = httpClientFactory.CreateClient();
        _httpClient.BaseAddress = new Uri("https://localhost:44318/api/v1/");
        _webHostEnvironment = webHostEnvironment;
    }

    [HttpGet]
    public async Task<IActionResult> Index(CancellationToken ct)
    {
        var response = await _httpClient.GetAsync("room-types", ct);

        if (!response.IsSuccessStatusCode) return StatusCode((int)response.StatusCode);

        var responseContent = await response.Content.ReadAsStringAsync(ct);
        var roomTypes = JsonConvert.DeserializeObject<List<RoomTypeListItemViewModel>>(responseContent);

        return View(roomTypes);
    }

    [HttpGet]
    public async Task<IActionResult> Details(Guid id, CancellationToken ct)
    {
        var response = await _httpClient.GetAsync($"room-types/{id}", ct);

        if (!response.IsSuccessStatusCode) return StatusCode((int)response.StatusCode);

        var responseContent = await response.Content.ReadAsStringAsync(ct);
        var roomType = JsonConvert.DeserializeObject<RoomTypeDetailsViewModel>(responseContent);

        return View(roomType);
    }

    [HttpGet]
    public async Task<IActionResult> Create(CancellationToken ct)
    {
        var response = await _httpClient.GetAsync("amenities", ct);
        if (!response.IsSuccessStatusCode) return StatusCode((int)response.StatusCode);

        var responseContent = await response.Content.ReadAsStringAsync(ct);
        var amenities = JsonConvert.DeserializeObject<List<AmenityViewModel>>(responseContent);

        var roomTypeViewModel = new RoomTypeCreateViewModel()
        {
            Amenities = amenities
        };
        return View(roomTypeViewModel);
    }

    [HttpPost]
    public async Task<IActionResult> Create(RoomTypeCreateViewModel viewModel, CancellationToken ct)
    {
        if (!ModelState.IsValid) return BadRequest();
        var createDto = new CreateRoomTypeDto()
        {
            Title = viewModel.Title,
            Description = viewModel.Description,
            Amenities = viewModel.SelectedAmenities,
            NightlyRate = viewModel.NightlyRate,
            MaxCapacity = viewModel.MaxCapacity,
            Images = new List<string>()
        };
        var files = HttpContext.Request.Form.Files;
        var webRootPath = _webHostEnvironment.WebRootPath;
        var upload = webRootPath + @"/images/roomType/";
        foreach (var file in files)
        {
            var fileName = Guid.NewGuid().ToString();
            var extension = Path.GetExtension(file.FileName);
            await using(var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
            {
                await file.CopyToAsync(fileStream, ct);
                createDto.Images.Add(fileName+extension);
            }
        }
        
        var requestContent = JsonContent.Create(createDto);
        var response = await _httpClient.PostAsync("room-types", requestContent, ct);
        if (!response.IsSuccessStatusCode) return StatusCode((int)response.StatusCode);
        return RedirectToAction("Index");
    }

    [HttpGet]
    public async Task<IActionResult> Edit(Guid id, CancellationToken ct)
    {
        var roomTypesResponse = await _httpClient.GetAsync($"room-types/{id}", ct);
        if (!roomTypesResponse.IsSuccessStatusCode) return StatusCode((int)roomTypesResponse.StatusCode);

        var responseContent = await roomTypesResponse.Content.ReadAsStringAsync(ct);
        
        var roomType = JsonConvert.DeserializeObject<RoomTypeEditViewModel>(responseContent);
        var amenitiesResponse = await _httpClient.GetAsync($"amenities", ct);
        if (!amenitiesResponse.IsSuccessStatusCode) return StatusCode((int)amenitiesResponse.StatusCode);

        var amenitiesResponseContent = await amenitiesResponse.Content.ReadAsStringAsync(ct);
        
        var amenities = JsonConvert.DeserializeObject<List<AmenityViewModel>>(amenitiesResponseContent);
        roomType.AvailableAmenities = amenities;
        return View(roomType);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(Guid id, RoomTypeEditViewModel viewModel, CancellationToken ct)
    {
        if (id != viewModel.Id)
        {
            return BadRequest();
        }

        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }

        var editDto = new EditRoomTypeDto()
        {
            Id = viewModel.Id,
            Title = viewModel.Title,
            Description = viewModel.Description,
            Images = new List<string>(),
            MaxCapacity = viewModel.MaxCapacity,
            NightlyRate = viewModel.NightlyRate,
            Amenities = viewModel.SelectedAmenities
        };
        
        var files = HttpContext.Request.Form.Files;
        if (files.Count > 0)
        {
            editDto.Images = new List<string>();
            var webRootPath = _webHostEnvironment.WebRootPath;
            var upload = webRootPath + @"/images/roomType/";
            foreach (var file in files)
            {
                var fileName = Guid.NewGuid().ToString();
                var extension = Path.GetExtension(file.FileName);
                await using (var fileStream =
                             new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                {
                    await file.CopyToAsync(fileStream, ct);
                    editDto.Images.Add(fileName + extension);
                }
            }
        }

        var requestContent = JsonContent.Create(editDto);
        var response = await _httpClient.PutAsync("room-types", requestContent, ct);

        if (response.IsSuccessStatusCode)
        {
            return RedirectToAction("Index");
        }

        return StatusCode((int)response.StatusCode);
    }

    public async Task<IActionResult> DeleteConfirmation(Guid id, CancellationToken ct)
    {
        var response = await _httpClient.GetAsync($"room-types/{id}", ct);

        if (!response.IsSuccessStatusCode) return StatusCode((int)response.StatusCode);

        var responseContent = await response.Content.ReadAsStringAsync(ct);
        var roomType = JsonConvert.DeserializeObject<RoomTypeDetailsViewModel>(responseContent);

        return View(roomType);
    }

    [HttpPost]
    public async Task<IActionResult> Delete(Guid id, CancellationToken ct)
    {
        var response = await _httpClient.DeleteAsync($"room-types/{id}", ct);
        if (response.IsSuccessStatusCode)
        {
            return RedirectToAction("Index");
        }

        return StatusCode((int)response.StatusCode);
    }
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"] - Hotel-Core</title>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Favicon Icon -->
    <link rel="shortcut icon" type="image/x-icon" href="~/images/favicon.ico">

    <!-- All css here -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/shortcode/shortcodes.css">
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/responsive.css">
</head>
<body>
<header class="header-area fixed header-sticky">
    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-md-4 col-sm-4 col-xs-12">
                <div class="logo">
                    <a asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="~/images/logo/logo.png" alt="HotelATR">
                    </a>
                </div>
            </div>
            <div class="col-lg-7 col-md-8 col-sm-8 hidden-xs">
                <div class="header-top fix">
                    <div class="header-contact">
                        <span class="text-theme">Контакты:</span>
                        <span>8-000-000-00-00</span>
                    </div>
                    <div class="header-links">
                        <a href="https://www.facebook.com/">
                            <i class="zmdi zmdi-facebook"></i>
                        </a>
                        <a href="https://twitter.com/">
                            <i class="zmdi zmdi-twitter"></i>
                        </a>
                        <a href="https://plus.google.com/">
                            <i class="zmdi zmdi-google-plus"></i>
                        </a>
                        <a href="https://www.instagram.com/">
                            <i class="zmdi zmdi-instagram"></i>
                        </a>
                        <a href="https://www.pinterest.com/">
                            <i class="zmdi zmdi-pinterest"></i>
                        </a>
                    </div>
                </div>
                <!-- Mainmenu Start -->
                <div class="main-menu hidden-xs">
                    <nav>
                        <ul>
                            <li>
                                <a asp-area="" asp-controller="Home" asp-action="Index">ГЛАВНАЯ</a>
                            </li>
                            <li>
                                <a asp-area="" asp-controller="RoomType" asp-action="Index">НОМЕРА</a>
                            </li>
                            <li>
                                <a href="#">АДМИНИСТРИРОВАНИЕ</a>
                                <ul class="submenu">
                                    <li>
                                        <a asp-area="" asp-controller="RoomTypeAdmin" asp-action="Index">Виды номеров</a>
                                    </li>
                                    <li>
                                        <a asp-area="" asp-controller="RoomAdmin" asp-action="Index">Номера</a>
                                    </li>
                                    <li>
                                        <a asp-area="" asp-controller="HotelBranch" asp-action="Index">Филиалы отелей</a>
                                    </li>
                                    <li>
                                        <a asp-area="" asp-controller="Amenity" asp-action="Index">Удобства номеров</a>
                                    </li>
                                    <li>
                                        <a asp-area="" asp-controller="ReservationAdmin" asp-action="Index">Бронирования</a>
                                    </li>
                                    <li>
                                        <a asp-area="" asp-controller="OccupiedRoom" asp-action="Index">Занятые номера</a>
                                    </li>
                                    <li>
                                        <a asp-area="" asp-controller="RoomService" asp-action="Index">УCЛУГИ В НОМЕР</a>
                                    </li>
                                    <li>
                                        <a asp-area="" asp-controller="OrderAdmin" asp-action="Index">ЗАКАЗЫ</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="#">ОБСЛУЖИВАНИЕ</a>
                                <ul class="submenu">
                                    <a asp-area="" asp-controller="" asp-action="">УСЛУГИ</a>
                                </ul>
                            </li>
                            <li>
                                <a href="contact.html">КОНТАКТЫ</a>
                            </li>
                        </ul>
                    </nav>
                </div>
                <!-- Mainmenu End -->
            </div>
        </div>
    </div>
</header>
<div>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>


<footer class="footer-area border-top footer text-muted">
    <!-- Footer Widget Start -->
    <div class="footer-widget-area bg-dark">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                    <div class="single-footer-widget">
                        <div class="footer-logo">
                            <a asp-area="" asp-controller="Home" asp-action="Index">
                                <img src="~/images/logo/footer-logo.png" alt="HotelATR">
                            </a>
                        </div>
                        <p>В наших отелях вы находите оазис уюта и роскоши в самых волнующих местах мира. Мы создаем атмосферу, в которой каждый гость чувствует себя как дома.</p>
                        <div class="social-icons">
                            <a href="https://www.facebook.com/">
                                <i class="zmdi zmdi-facebook"></i>
                            </a>
                            <a href="https://www.instagram.com/">
                                <i class="zmdi zmdi-instagram"></i>
                            </a>
                            <a href="https://www.rss.com/">
                                <i class="zmdi zmdi-rss"></i>
                            </a>
                            <a href="https://twitter.com/">
                                <i class="zmdi zmdi-twitter"></i>
                            </a>
                            <a href="https://www.pinterest.com/">
                                <i class="zmdi zmdi-pinterest"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                    <div class="single-footer-widget">
                        <h3>Свяжитесь с нами</h3>
                        <div class="c-info">
                            <span>
                                <i class="zmdi zmdi-pin"></i>
                            </span>
                            <span>Улица Байтурсынұлы 126/1, Алматы</span>
                        </div>
                        <div class="c-info">
                            <span>
                                <i class="zmdi zmdi-email"></i>
                            </span>
                            <span>med.maratov@aues.com<br/>med.maratov@aues.kz<br/></span>
                        </div>
                        <div class="c-info">
                            <span>
                                <i class="zmdi zmdi-phone"></i>
                            </span>
                            <span>+7-000-000-00-00<br>+7-000-000-00-00</span>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 hidden-md hidden-sm col-xs-12">
                    <div class="single-footer-widget">
                        <h3>Переходы</h3>
                        <ul class="footer-list">
                            <li>
                                <a asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                            </li>
                            <li>
                                <a href="room-grid.html">Комнаты</a>
                            </li>
                            <li>
                                <a href="event.html">Мероприятия</a>
                            </li>
                            <li>
                                <a href="contact.html">Контакты</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="single-footer-widget">
                        <h3>Коллекция</h3>
                        <div class="instagram-image">
                            <div class="footer-img">
                                <a href="room-grid.html">
                                    <img src="~/images/footer/1.jpg" alt="">
                                </a>
                            </div>
                            <div class="footer-img">
                                <a href="room-grid.html">
                                    <img src="~/images/footer/2.jpg" alt="">
                                </a>
                            </div>
                            <div class="footer-img">
                                <a href="room-grid.html">
                                    <img src="~/images/footer/3.jpg" alt="">
                                </a>
                            </div>
                            <div class="footer-img">
                                <a href="room-grid.html">
                                    <img src="~/images/footer/4.jpg" alt="">
                                </a>
                            </div>
                            <div class="footer-img">
                                <a href="room-grid.html">
                                    <img src="~/images/footer/5.jpg" alt="">
                                </a>
                            </div>
                            <div class="footer-img">
                                <a href="room-grid.html">
                                    <img src="~/images/footer/6.jpg" alt="">
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer Widget End -->
    <!-- Footer Bottom Area Start -->
    <div class="footer-bottom-area bg-black">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="footer-text text-center">
                        <span>&copy; 2024 Hotel-X - Все права защищены.</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer Bottom Area End -->
</footer>
<!-- Footer Area End -->
<script src="~/js/vendor/modernizr-2.8.3.min.js"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/js/vendor/jquery-1.12.4.min.js"></script>
<script src="~/js/bootstrap.min.js"></script>
<script src="~/js/owl.carousel.min.js"></script>
<script src="~/js/ajax-mail.js"></script>
<script src="~/js/jquery.ajaxchimp.min.js"></script>
<script src="~/js/jquery.meanmenu.js"></script>
<script src="~/js/jquery.counterup.min.js"></script>
<script src="~/js/waypoints.min.js"></script>
<script src="~/js/isotope.pkgd.min.js"></script>
<script src="~/js/imagesloaded.pkgd.min.js"></script>
<script src="~/js/jquery.magnific-popup.js"></script>
<script src="~/js/plugins.js"></script>
<script src="~/js/main.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>